apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trustyai-runtime
  namespace: devcluster-monitoring
spec:
  namespaceSelector:
    matchNames:
      - vllm
  selector:
    matchLabels:
      app: trustyai-service
  endpoints:
    - port: http
      interval: 30s
      path: /q/metrics